services:
  web:
    container_name: apache
    ports:
      - "80:80"
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  pma:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1024M
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    links:
      - db:db

  db:
    image: mariadb:latest
    container_name: maria
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test