services:
  web:
    image: php:8.0.1-apache
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - sucre

  pma:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 1024M
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    links:
      - db:db
    networks:
      - sucre

  db:
    image: mariadb:latest
    container_name: maria
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - sucre
networks:
  sucre:
    driver: bridge